djangoprojekti/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pelikauppa/', include('pelikauppa.urls')),
    url(r'^', include('pelikauppa.urls')),
]

pelikauppa/urls.py
from django.conf.urls import url
from . import views

app_name = 'pelikauppa'

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^register/$', views.register, name='register'),
        url(r'^activate/(?P<key>.+)$', views.activate, name='activate'),
        url(r'^login_user/$', views.login_user, name='login_user'),
        url(r'^logout_user/$', views.logout_user, name='logout_user'),
        url(r'^developer_add_game/$', views.developer_add_game, name='developer_add_game'),
        url(r'^developer_remove_game/$', views.developer_remove_game, name='developer_remove_game'),
        url(r'^game_view/$', views.game_view, name='game_view'),
        url(r'^save_game_data/$', views.save_game_data, name='save_game_data'),
        url(r'^load_game_data/$', views.load_game_data, name='load_game_data'),
        url(r'^submit_high_score/$', views.submit_high_score, name='submit_high_score'),
        url(r'^add_game_to_player/$', views.add_game_to_player, name='add_game_to_player'),
        url(r'^open_game_view/$', views.open_game_view, name='open_game_view'),
        url(r'^player_starting_view/$', views.player_starting_view, name='player_starting_view'),
        url(r'^purchase/$', views.purchase, name='purchase'),
        url(r'^purchase_success/', views.purchase_success, name='purchase_success'),
        url(r'^purchase_cancel/$', views.purchase_cancel, name='purchase_cancel'),
        url(r'^purchase_error/$', views.purchase_error, name='purchase_error'),
        url(r'^general_error/$', views.general_error, name='general_error'),
        url(r'^game_sales/$', views.game_sales, name='game_sales'),
        ]

pelikauppa/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from datetime import datetime


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_developer = models.BooleanField(default=False)

class Game(models.Model):
    name = models.CharField(max_length = 100, unique=True)
    developer = models.ForeignKey(User, on_delete=models.CASCADE,
            related_name='games')
    url = models.URLField()
    price = models.DecimalField(max_digits=5, decimal_places=2)


# key to owner, key to game, json for saves
class GameOwnerships(models.Model):
    gameOwner = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    data = models.CharField(max_length = 500, null=True)
    high_score = models.DecimalField(max_digits=5, decimal_places=0, null=True)

class Purchase(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    time = models.DateTimeField()

pelikauppa/forms.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from pelikauppa.models import Profile, Game

class UserForm(forms.ModelForm):
    username = forms.CharField(label='Käyttäjätunnus')
    password = forms.CharField(widget=forms.PasswordInput, label='Salasana')
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Vahvista salasana')
    email = forms.EmailField(required=True, label='Sähköposti')

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class UserProfileForm(forms.ModelForm):
    is_developer = forms.BooleanField(label='Rekisteröidy kehittäjänä:', required=False)

    class Meta:
        model = Profile
        exclude = ['user']

class GameForm(forms.ModelForm):
    name = forms.CharField(label='Pelin nimi', required=True)
    url = forms.URLField(label='Pelin URL', required=True)
    price = forms.DecimalField(label='Pelin hinta', max_digits=5, decimal_places=2, min_value=0)

    class Meta:
        model = Game
        exclude = ['developer']

pelikauppa/views.py
from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from .models import Profile, Game, GameOwnerships, Purchase
from .forms import UserForm, UserProfileForm, GameForm
from django.template import RequestContext
from django.core import mail
from django.contrib.auth.models import User
from hashlib import md5
from django.urls import reverse
import json
from datetime import datetime

# The main page of the website.
def index(request):
    return render(request, template_name='pelikauppa/index.html')

# The general error message used in miscellaneous situations.
def general_error(request):
    return render(request, template_name='pelikauppa/general_error.html')

# User registration.
def register(request):
    if request.method == 'POST':
        userform = UserForm(request.POST, prefix='user')
        profileform = UserProfileForm(request.POST, prefix='userprofile')

        if (userform.is_valid() and profileform.is_valid and
                userform.cleaned_data['password'] == userform.cleaned_data[
                    'confirm_password']):
            user = userform.save(commit=False)
            user.set_password(userform.cleaned_data['password'])
            user.is_active = False
            user.save()
            userprofile = profileform.save(commit=False)
            userprofile.user = user
            userprofile.save()

            # Send confirmation email
            with mail.get_connection() as connection:
                confirmation_link = 'http://' + str(request.get_host()) + str(reverse('pelikauppa:activate', args=[user.pk]))
                mail.EmailMessage('Tunnuksen aktivointi', confirmation_link,
                'pelikauppa@pelikauppa.com', [user.email],
                connection=connection).send()

            return render(request, 'pelikauppa/message.html',
                    dict(message='Rekisteröinti onnistui. Aktivoi tili sähköpostiin tulleella vahvistuslinkillä.'))
    else:
        userform = UserForm(prefix='user')
        profileform = UserProfileForm(prefix='userprofile')

    return render(request, 'pelikauppa/register.html',
            dict(userform=userform,userprofileform=profileform))

# The user account activation (mockup, doesn't actually use an email activation)
def activate(request, key):
    user = get_object_or_404(User, pk=key)
    if user.is_active == False:
        user.is_active = True
        user.save()

    return render(request, 'pelikauppa/message.html',
            dict(message='Aktivointi onnistui, voit nyt kirjautua sisään.'))


# Checks whether user logging in has a valid credentials and whether they are
# a player or a developer.
def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if user.profile.is_developer:
                    return redirect(reverse('pelikauppa:developer_add_game'))
                else:

                    return redirect(reverse('pelikauppa:add_game_to_player'))

            else:
                # Error message for disabled account
                pass
    return render(request, template_name='pelikauppa/login.html')

def logout_user(request):
    logout(request)
    return redirect(reverse('pelikauppa:index'))

# The page where the individual games are played.
def game_view(request):
    return render(request, template_name='pelikauppa/game_view.html')

# Called when an user saves their data from within the JavaScript game.
def save_game_data(request):
    if request.method == 'POST':

        query_dict = request.POST


        json_msg = query_dict['json_msg']
        json_to_dict = json.loads(json_msg)
        game_url = json_to_dict['gameURL']
        curr_user_name = json_to_dict['currUser']
        curr_user = User.objects.get(username=curr_user_name)
        curr_game = Game.objects.get(url=game_url)
        curr_ownership = GameOwnerships.objects.get(game=curr_game, gameOwner=curr_user)

        curr_ownership.data = json_msg

        curr_ownership.save()

        return HttpResponse('Success')

# Used when user loads data.
def load_game_data(request):

    if request.method == 'GET':

        query_dict = request.GET
        game_url = query_dict['gameURL']
        curr_user_name = query_dict['currUser']
        curr_user = User.objects.get(username=curr_user_name)
        curr_game = Game.objects.get(url=game_url)
        curr_ownership = GameOwnerships.objects.get(game=curr_game, gameOwner=curr_user)


        if (curr_ownership.data != None):
            return HttpResponse(curr_ownership.data)

        return HttpResponse('empty')

# Called when user submits their score.
def submit_high_score(request):
    if request.method == 'POST':
        query_dict = request.POST

        game_url = query_dict['gameURL']
        curr_user_name = query_dict['currUser']
        curr_user = User.objects.get(username=curr_user_name)
        curr_game = Game.objects.get(url=game_url)
        curr_ownership = GameOwnerships.objects.get(game=curr_game, gameOwner=curr_user)
        if (curr_ownership.high_score is None or float(query_dict['score']) > curr_ownership.high_score):
            curr_ownership.high_score = float(query_dict['score'])
            curr_ownership.save()
        return HttpResponse('Success')

# Developer basic page. Has functionality to add new games or remove existing ones.
def developer_add_game(request):
    if not request.user.profile.is_developer:
        return general_error(request)

    if request.method == 'POST':
        game_form = GameForm(request.POST, prefix='game')

        if (game_form.is_valid()):
            game = game_form.save(commit=False)
            game.developer = request.user
            game.save()
            return render(request, 'pelikauppa/message.html',
                    dict(message='Peli lisätty.'))
    else:
        game_form = GameForm(prefix='game')
    dev_game_list = Game.objects.filter(developer=request.user)
    return render(request, 'pelikauppa/developer_add_game.html',
            dict(gameform=game_form, devgamelist=dev_game_list))

# Called when a developer removes their game.
def developer_remove_game(request):
    if not request.user.profile.is_developer:
        return general_error(request)

    if request.method == 'POST':
        game_to_be_removed = Game.objects.get(pk=request.POST.get('selected_game'))
        game_to_be_removed.delete()

        return developer_add_game(request)

    else:
        return general_error(request)


# Player list view of all games and all player's games.
def player_starting_view(request):
    store_game_list = Game.objects.all()
    player_game_list = []
    if request.user.is_authenticated:
        player_game_ownerships = GameOwnerships.objects.filter(gameOwner=request.user)
        for ownership in player_game_ownerships:
            player_game_list.append(ownership.game)
    return render(request, 'pelikauppa/game_list.html',
                  dict(allgames=store_game_list, playergames=player_game_list))

# Adds a game to player's game library.
def add_game_to_player(request):
    if request.method == 'POST':
        ownership = GameOwnerships()
        ownership.gameOwner = request.user

        ownership.game = Game.objects.get(name=request.POST.get('selected_game'))
        ownership.save()

        purchase = Purchase()
        purchase.game = Game.objects.get(name=request.POST.get('selected_game'))
        purchase.time = datetime.now()
        purchase.save()

    return player_starting_view(request)

# Opens the single game view where the game is played.
def open_game_view(request):
    game_url = request.POST.get('selected_game_url')

    curr_game = Game.objects.get(url=game_url)
    game_ownerships = GameOwnerships.objects.filter(game=curr_game)

    high_score_list = []
    for ownership in game_ownerships:
        item = { 'name': ownership.gameOwner,
            'highscore': ownership.high_score }
        if ownership.high_score is not None:
            high_score_list.append(item)
    high_score_list.sort(key=lambda value: value['highscore'], reverse=True)

    return render(request, 'pelikauppa/game_view.html', dict(gameurl=game_url, curruser=request.user,
                                                                highscores=high_score_list))


# Handles the purchase.
def purchase(request):
    if not request.user.is_authenticated:
        return redirect(reverse('pelikauppa:login_user'))
    #if request.method == 'POST':
    #pid = "ostos1"
    sid = "wsd17kevat17"
    game = Game.objects.get(pk=request.POST.get('selected_game'))
    pid = str(game.name)
    amount = str(game.price)
    #amount = "50"
    secret_key = "abd51612a6c33bd3828e92a5f64f93f2"
    checksumstr = "pid={}&sid={}&amount={}&token={}".format(pid, sid, amount, secret_key)
    # checksumstr is the string concatenated above
    m = md5(checksumstr.encode("ascii"))
    checksum = m.hexdigest()
    # checksum is the value that should be used in the payment request
    return render(request, "pelikauppa/purchase.html",
            {'pid':pid, 'sid':sid, 'amount':amount, 'checksum':checksum})

def purchase_cancel(request):
    return render(request, 'pelikauppa/purchase_cancel.html')

def purchase_error(request):
    return render(request, 'pelikauppa/purchase_error.html')

# Called if the payment service OK's the payment. Checksum is checked here.
def purchase_success(request):
    pid = request.GET.get('pid')
    ref = request.GET.get('ref')
    result = request.GET.get('result')
    checksum = request.GET.get('checksum')
    secret_key = "abd51612a6c33bd3828e92a5f64f93f2"

pelikauppa/templates/pelikauppa/base.html
<!DOCTYPE html>
<meta charset='utf-8'>

<!-- Latest compiled and minified JQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Latest compiled and minified CSS -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<!--
<link rel="stylesheet" href="https://bootswatch.com/yeti/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
-->
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile displbay -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#coll-navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'pelikauppa:index' %}">Pelikauppa</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="coll-navbar">
            <ul class="nav navbar-nav">
                {% if request.user.profile.is_developer %}
                <li><a href="{% url 'pelikauppa:developer_add_game' %}">Katso ja lisää pelejä</a></li>
                {% else %}
                <li><a href="{% url 'pelikauppa:player_starting_view' %}">Katso ja osta pelejä</a></li>
                {% endif %}

            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'pelikauppa:logout_user' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'pelikauppa:login_user' %}">Login</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block content %} {% endblock %}

pelikauppa/templates/pelikauppa/developer_add_game.html
{% extends "pelikauppa/base.html" %}
{% block content %}
<h4>Lisää peli:</h4>
<form id='add_game' action="{% url 'pelikauppa:developer_add_game'%}" method="post">
    {% csrf_token %}
    {% for field in gameform %}
        <div> {{field.label_tag}} {{field}}</div>
    {% endfor %}
    <button type="submit">Submit</button>
</form>

<h4>Lista sinun peleistäsi:</h3>
{% for field in devgamelist %}
    <label> {{field.name}} </label>
    <form action="{% url 'pelikauppa:developer_remove_game'%}"
        method='post' style="display: inline;">
        {% csrf_token %}
        <button type="submit" name='selected_game' value={{field.pk}}>Poista peli</button>
    </form>

    <form action="{% url 'pelikauppa:game_sales'%}" method='post' style="display: inline;">
        {% csrf_token %}
        <button type="submit" name='selected_game' value={{field.pk}}>Myyntitilastot</button>
    </form>
{% endfor %}

{% endblock %}

pelikauppa/templates/pelikauppa/game_list.html
{% extends "pelikauppa/base.html" %}
{% block content %}

{% if user.is_authenticated %}
<h3>Lista kaikista sinun peleistäsi:</h3>
<ul>
{% for game in playergames %}
<li>
    <form action="{% url 'pelikauppa:open_game_view'%}" method='post'>
        {% csrf_token %}
        {{game.name}} | 
        <button type="submit" name='selected_game_url' value={{game.url}}>Pelaa peliä</button>
    </form>
</li>
{% endfor %}
</ul>
{% endif %}

<h3>Lista kaikista kaupan peleistä:</h3>
<ul>
{% for field in allgames %}

<li>
    {% if field in playergames %}
        {{field.name}} | Omistat tämän pelin.
    {% else %}
        <form action="{% url 'pelikauppa:purchase'%}" method='post'>
            {% csrf_token %}
            {{field.name}} | {{field.price}} € | 
            <button type="submit"name='selected_game' value={{field.pk}}>Osta peli</button>
        </form>
    {% endif %}
</li>

{% endfor %}

</ul>
{% endblock %}

pelikauppa/templates/pelikauppa/game_sales.html
{% extends "pelikauppa/base.html" %}
{% block content %}

{% if user.is_authenticated %}
<h3>Pelisi myyntitilastot:</h3>
<ul>
{% for purchase in list %}
<li>
    {{purchase.time}}
</li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

pelikauppa/templates/pelikauppa/game_view.html
{% extends "pelikauppa/base.html" %}
{% block content %}
<head>
    {% csrf_token %}
    <script source = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" >

        var score = 0;
        var speedFactor = 0;
        var json_data;

        // Allow post messages without csrf-token.
        $.ajaxSetup({
            headers: { "X-CSRFToken": getCookie("csrftoken") }
        });

        function getCookie(c_name)
        {
            if (document.cookie.length > 0)
            {
                c_start = document.cookie.indexOf(c_name + "=");
                if (c_start != -1)
                {
                    c_start = c_start + c_name.length + 1;
                    c_end = document.cookie.indexOf(";", c_start);
                    if (c_end == -1) c_end = document.cookie.length;
                    return unescape(document.cookie.substring(c_start,c_end));
                }
            }
            return "";
        }
        // Listen for the messages from the JavaScript game.
        window.addEventListener("message", function(evt)
        {
            var iFrame = document.getElementById( 'iFrame1' );
            iFrame.contentWindow.focus();

            if(evt.data.messageType === "SETTING")
            {
                iFrame.width = evt.data.options.width;
                iFrame.height = evt.data.options.height;
            }
            else if(evt.data.messageType === "SAVE")
            {
                score = evt.data.gameState.score;
                speedFactor = evt.data.gameState.speedFactor;
                var msg =
                {
                    gameURL: "{{gameurl}}",
                    currUser: "{{curruser}}",
                    gameState:
                    {
                        score: parseFloat(score),
                        speedFactor: parseFloat(speedFactor)
                    }
                };

                json_msg = JSON.stringify(msg);
                $.post('http://{{ request.get_host }}{% url 'pelikauppa:save_game_data' %}', {json_msg:json_msg});

            }
            else if(evt.data.messageType === "SCORE")
            {
                $.post('http://{{ request.get_host }}{% url 'pelikauppa:submit_high_score' %}', {"gameURL":"{{gameurl}}",
                                                    "currUser":"{{curruser}}", "score":evt.data.score});
            }
            else if(evt.data.messageType === "LOAD_REQUEST")
            {
                $.get('http://{{ request.get_host }}{% url 'pelikauppa:load_game_data' %}', {"gameURL":"{{gameurl}}", "currUser":"{{curruser}}"},
                function(data)
                {
                    json_data = JSON.parse(data);

                    var msg =
                    {
                        "messageType": "LOAD",
                        "gameState":
                        {
                            "score": parseFloat(json_data['gameState']['score']),
                            "speedFactor": parseFloat(json_data['gameState']['speedFactor'])
                        }
                    };
                    var frameWindow = iFrame.contentWindow;
                    frameWindow.postMessage(msg, "*");
                });
            }
        });
    </script>
</head>
<body>
    <div style="width: 100%; overflow: hidden;">
        <div style="width: 600px; float: left;">
            <iframe src='{{gameurl}}', id='iFrame1'></iframe>
        </div>
        <div style="margin-left: 650px;">
            <ul>
                <h2>Ennätykset:</h2>
                <table style="width:100%">
                    <tr>
                        <th>Pelaaja</th>
                        <th>Tulos</th>
                    </tr>
                    {% for item in highscores %}
                    <tr>
                        <td>
                            {{item.name}}
                        </td>
                        <td>
                            {{item.highscore}}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
        </div>
    </div>
</body>

{% endblock %}

pelikauppa/templates/pelikauppa/general_error.html
{% extends "pelikauppa/base.html" %}
{% block content %}
<h2>Tapahtui virhe. Pahoittelemme tapahtunutta.</h2>
<ul>
    <li><a href="{% url 'pelikauppa:index' %}">Palaa etusivulle.</a></li>
</ul>
{% endblock %}

pelikauppa/templates/pelikauppa/index.html
{% extends "pelikauppa/base.html" %}
{% block content %}
<h1>Tervetuloa maailman parhaimpaan pelikauppaan!!</h1>
{% endblock %}

pelikauppa/templates/pelikauppa/login.html
{% extends "pelikauppa/base.html" %}
{% block content %}

<title>Kirjaudu sisään</title>
<h3>Kirjaudu sisään</h3>
<form action="{% url 'pelikauppa:login_user'%}" method="post">
    {% csrf_token %}
    <label>Käyttäjätunnus:</label>
    <div>
        <input id="id_username" name="username" type="text">
    </div>
    <label>Salasana:</label>
    <div>
        <input id="id_password" name="password" type="password">
    </div>
    <div>
        <button type="submit" class="btn btn-success">Submit</button>
    </div>
    <div>
        <a href="{% url 'pelikauppa:register' %}">Rekisteröidy.</a>
    </div>

</form>
{% endblock %}

pelikauppa/templates/pelikauppa/message.html
{% extends "pelikauppa/base.html" %}
{% block content %}
<p>{{ message }}</p>
{% endblock %}

pelikauppa/templates/pelikauppa/purchase.html
{% extends "pelikauppa/base.html" %}
{% block content %}
<h2>Pelikauppa</h2>
<form action="http://simplepayments.herokuapp.com/pay/" method="POST">
    <input type="hidden" name="pid" value= "{{pid}}" />
    <input type="hidden" name="sid" value= "{{sid}}" />
    <input type="hidden" name="success_url"
                         value="http://{{ request.get_host }}{% url 'pelikauppa:purchase_success' %}" />
    <input type="hidden" name="cancel_url"
            value="http://{{ request.get_host }}{% url 'pelikauppa:purchase_cancel' %}" />
    <input type="hidden" name="error_url"
            value="http://{{ request.get_host }}{% url 'pelikauppa:purchase_error' %}" />
    <input type="hidden" name="checksum"
            value="{{checksum}}" />

    <input type="hidden" id="id_amount" name="amount" value="{{amount}}" />
    <input type="submit" value="Accept Payment"/>
</form>

<ul>
    <li><a href="{% url 'pelikauppa:purchase_cancel' %}">Peruuta</a></li>
</ul>
{% endblock %}

pelikauppa/templates/pelikauppa/purchase_cancel.html
{% extends "pelikauppa/base.html" %}
{% block content %}
<h2>Maksutapahtuma peruutettiin.</h2>
<ul>
    <li><a href="{% url 'pelikauppa:player_starting_view' %}">Palaa</a></li>
</ul>
{% endblock %}

pelikauppa/templates/pelikauppa/purchase_error.html
{% extends "pelikauppa/base.html" %}
{% block content %}
<h2>Maksamisessa tapahtui virhe.</h2>
<ul>
    <li><a href="{% url 'pelikauppa:player_starting_view' %}">Palaa</a></li>
</ul>
{% endblock %}

pelikauppa/templates/pelikauppa/purchase_success.html
{% extends "pelikauppa/base.html" %}
{% block content %}
<h2>Maksaminen onnistui.</h2>
<ul>
  <form action="{% url 'pelikauppa:add_game_to_player'%}" method='POST'>
      {% csrf_token %}
      <button type="submit" name='selected_game' value={{pid}}>Paluu</button>
  </form>
</ul>
{% endblock %}

pelikauppa/templates/pelikauppa/register.html
{% extends "pelikauppa/base.html" %}
{% block content %}

<h3>Rekisteröidy</h3>

<form id='rekisteräidy' action="" method="post">
    {% csrf_token %}
    {% for field in userform %}
    <label> {{field.label_tag}} </label>
    <div> {{field}} </div>
    {% endfor %}
    {% for field in userprofileform %}
    <label> {{field.label_tag}} </label>
    <div> {{field}} </div>
    {% endfor %}
    <button type="submit">Submit</button>
</form>
{% endblock %}